name: Earrape
main: com.redafex.Earrape
version: 4.0.0
description: This plugin earrapes members of your server :)

commands:
  earrape:
    usage: /earrape
    description: It makes the victim jump out of his chair
    permission: earrape.permission
    permission-message: You don't have permssions to earrape someone

permissions:
  earrape.permission:
    default: op